apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: staging
spec:
  type: ClusterIP # Diubah dari NodePort agar lebih secure
  selector:
    app: flask-web
  ports:
    - protocol: TCP
      port: 80         # Port yang dipanggil oleh Ingress
      targetPort: 5000 # Port aplikasi di dalam Container