name: DevSecOps Pipeline

on:
  push:
    branches: [ "staging", "main" ]

jobs:
  sast_bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install bandit && bandit -r app/

  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install pytest pytest-cov
          pytest --cov=app --cov-report=xml tests/
      - uses: actions/upload-artifact@v4
        with: { name: coverage-xml, path: coverage.xml }

  sonarqube_check:
    needs: [unit_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/download-artifact@v4
        with: { name: coverage-xml }
      - uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build_job:
    needs: [sonarqube_check, sast_bandit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker build -t kikyputraa/sast-scan-test:${{ github.sha }} .
          docker save kikyputraa/sast-scan-test:${{ github.sha }} > app_image.tar
      - uses: actions/upload-artifact@v4
        with: { name: app-image, path: app_image.tar }

  security_check:
    needs: [build_job]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with: { name: app-image }
      - name: Trivy Scan (Focus on Fixable App Sec)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'kikyputraa/sast-scan-test:${{ github.sha }}'
          input: 'app_image.tar'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          vuln-type: 'os,library'

  push_job:
    needs: [security_check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with: { name: app-image }
      - run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
          docker load < app_image.tar
          docker push kikyputraa/sast-scan-test:${{ github.sha }}
          docker tag kikyputraa/sast-scan-test:${{ github.sha }} kikyputraa/sast-scan-test:latest
          docker push kikyputraa/sast-scan-test:latest

  deploy_job:
    needs: [push_job]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            NAMESPACE="default"; PORT="30001"
          else
            NAMESPACE="staging"; PORT="30002"
          fi
          sed -i "s|namespace:.*|namespace: $NAMESPACE|g" k8s/deployment.yaml
          sed -i "s|nodePort:.*|nodePort: $PORT|g" k8s/service.yml
          sed -i "s|image:.*|image: kikyputraa/sast-scan-test:${{ github.sha }}|g" k8s/deployment.yaml