name: CI/CD Pipeline

on:
  push:
    branches: [ main, staging ]

env:
  DOCKER_USER: "kikyputraa"
  DOCKER_IMAGE: "kikyputraa/sast-scan-test"

jobs:
  sast_and_test:
    name: Code Analysis & Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies & Run Tests
        run: |
          pip install pytest pytest-cov
          pytest --cov=app --cov-report=xml tests/

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG_KEY }}
            -Dsonar.sources=.
            -Dsonar.python.coverage.reportPaths=coverage.xml

  build_and_security:
    name: Build and Security Scan
    needs: sast_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t ${{ env.DOCKER_IMAGE }}:${{ github.sha }} .

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.DOCKER_IMAGE }}:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Login to Docker Hub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image
        if: success()
        run: |
          docker push ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          docker tag ${{ env.DOCKER_IMAGE }}:${{ github.sha }} ${{ env.DOCKER_IMAGE }}:latest
          docker push ${{ env.DOCKER_IMAGE }}:latest

  deploy:
    name: Deploy to K8s
    needs: build_and_security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare Manifests
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            NAMESPACE="default"
            PORT="30001"
          else
            NAMESPACE="staging"
            PORT="30002"
          fi
          sed -i "s|namespace:.*|namespace: $NAMESPACE|g" k8s/deployment.yaml
          sed -i "s|namespace:.*|namespace: $NAMESPACE|g" k8s/service.yml
          sed -i "s|nodePort:.*|nodePort: $PORT|g" k8s/service.yml
          sed -i "s|image:.*|image: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}|g" k8s/deployment.yaml
          echo "Deployment ready for $NAMESPACE"