name: DevSecOps Pipeline

on:
  push:
    branches: [ "main", "staging" ]

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Bandit (SAST)
        run: |
          pip install bandit
          bandit -r app/

  build-and-push:
    needs: sast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/sast-scan-test:${{ github.sha }}
            ${{ secrets.DOCKER_USER }}/sast-scan-test:latest

  deploy-config:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Logika Staging
      - name: Configure Staging Manifest
        if: github.ref == 'refs/heads/staging'
        run: |
          sed -i "s|namespace:.*|namespace: staging|g" k8s/deployment.yaml
          sed -i "s|namespace:.*|namespace: staging|g" k8s/service.yml
          sed -i "s|nodePort: 30001|nodePort: 30002|g" k8s/service.yml
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USER }}/sast-scan-test:${{ github.sha }}|g" k8s/deployment.yaml
          echo "Manifest Staging Ready"

      # Logika Production
      - name: Configure Production Manifest
        if: github.ref == 'refs/heads/main'
        run: |
          sed -i "s|namespace:.*|namespace: default|g" k8s/deployment.yaml
          sed -i "s|namespace:.*|namespace: default|g" k8s/service.yml
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USER }}/sast-scan-test:${{ github.sha }}|g" k8s/deployment.yaml
          echo "Manifest Production Ready"
