name: DevSecOps Pipeline

on:
  push:
    branches: [ "staging", "main" ]

jobs:
  sast_and_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Unit Test & Coverage
        run: |
          pip install pytest pytest-cov bandit
          pytest --cov=app --cov-report=xml tests/
          bandit -r app/
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with: { name: coverage-xml, path: coverage.xml }

  build_and_security:
    needs: sast_and_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t kikyputraa/sast-scan-test:${{ github.sha }} .
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'kikyputraa/sast-scan-test:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
      - name: Push to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
          docker push kikyputraa/sast-scan-test:${{ github.sha }}
          docker tag kikyputraa/sast-scan-test:${{ github.sha }} kikyputraa/sast-scan-test:latest
          docker push kikyputraa/sast-scan-test:latest

  deploy_simulation:
    needs: build_and_security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update K8s Manifests (Logic 15/01)
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            NAMESPACE="default"; PORT="30001"
          else
            NAMESPACE="staging"; PORT="30002"
          fi
          sed -i "s|namespace:.*|namespace: $NAMESPACE|g" k8s/deployment.yaml
          sed -i "s|nodePort:.*|nodePort: $PORT|g" k8s/service.yml
          sed -i "s|image:.*|image: kikyputraa/sast-scan-test:${{ github.sha }}|g" k8s/deployment.yaml
          echo "Verified for $NAMESPACE"